### ISSUE TITLE
Two errors on new druids

### ISSUE THREAD

**Issue by ghost** [Vae2009/ConRO_Druid#1]
`2x ConRO_Druid/druid.lua:139: attempt to index global 'Racial' (a nil value)
[string "@ConRO_Druid/druid.lua"]:139: in function `NextSpell'
[string "@ConRO/core.lua"]:2389: in function `?'
[string "@AckisRecipeList/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...s/AckisRecipeList/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
_ = <table> {
 AbilityPurge = <function> defined @ConRO/buttons.lua:2790
 IsPvP = <function> defined @ConRO/helper.lua:48
 DestroyPurgableOverlays = <function> defined @ConRO/buttons.lua:1712
 modules = <table> {
 }
 CancelTimer = <function> defined @AckisRecipeList/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DefFetchBlizzard = <function> defined @ConRO/buttons.lua:2266
 ItemEquipped = <function> defined @ConRO/helper.lua:145
 PurgeWindowFrame = <function> defined @ConRO/buttons.lua:1075
 InterruptGlow = <function> defined @ConRO/buttons.lua:1875
 ScheduleTimer = <function> defined @AckisRecipeList/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @ConRO/helper.lua:67
 CreateDefenseOverlay = <function> defined @ConRO/buttons.lua:1282
 Heroism = <function> defined @ConRO/helper.lua:310
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @ConRO/core.lua:2427
 ClearAbilityRaidBuffsIndependent = <function> defined @ConRO/buttons.lua:2719
 CreateRaidBuffsOverlay = <function> defined @ConRO/buttons.lua:1546
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @ConRO/helper.lua:241
 DisplayNext2WindowFrame = <function> defined @ConRO/buttons.lua:900
 NewModule = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 GlowNextDef = <function> defined @ConRO/buttons.lua:2920
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @ConRO/buttons.lua:1216
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @ConRO/helper.lua:732
 Dump = <function> defined @ConRO/buttons.lua:2627
 Colors = <table> {
 }
 RaidBuff = <function> defined @ConRO/helper.lua:398
 ClearAbilityInterruptIndependent = <function> defined @ConRO/buttons.lua:2695
 ToggleDamage = <function> defined @ConRO/buttons.lua:718
 Disable = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @ConRO/core.lua:2287
 Print = <function> defined @ConRO/core.lua:2036
 BurstMode = <function> defined @ConRO/helper.lua:79
 LEARNED_SPELL_IN_TAB = <function> defined @ConRO/core.lua:2362
 HideTauntGlow = <function> defined @ConRO/buttons.lua:1983
 HideDefenseGlow = <function> defined @ConRO/buttons.lua:1959
 CreateBurstButton = <function> defined @ConRO/buttons.lua:483
 Totem = <function> defined @ConRO/helper.lua:990
 SlashUnlock = <function> defined @ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @ConRO/helper.lua:816
 EnableModule = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 RaidBuffsFramePool = <table> {
 }
 DefenseFramePool = <table> {
 }
 BlockAoE = <function> defined @ConRO/buttons.lua:759
 Interrupt = <function> defined @ConRO/helper.lua:928
 ButtonFetch = <function> defined @ConRO/core.lua:2362
 ACTIONBAR_HIDEGRID = <function> defined @AddOns`

`2x ConRO_Druid/druid.lua:172: attempt to index global 'Racial' (a nil value)
[string "@ConRO_Druid/druid.lua"]:172: in function `NextDef'
[string "@ConRO/core.lua"]:2432: in function `?'
[string "@AckisRecipeList/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...s/AckisRecipeList/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
_ = <table> {
 AbilityPurge = <function> defined @ConRO/buttons.lua:2790
 IsPvP = <function> defined @ConRO/helper.lua:48
 DestroyPurgableOverlays = <function> defined @ConRO/buttons.lua:1712
 modules = <table> {
 }
 CancelTimer = <function> defined @AckisRecipeList/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DefFetchBlizzard = <function> defined @ConRO/buttons.lua:2266
 ItemEquipped = <function> defined @ConRO/helper.lua:145
 PurgeWindowFrame = <function> defined @ConRO/buttons.lua:1075
 InterruptGlow = <function> defined @ConRO/buttons.lua:1875
 ScheduleTimer = <function> defined @AckisRecipeList/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @ConRO/helper.lua:67
 CreateDefenseOverlay = <function> defined @ConRO/buttons.lua:1282
 Heroism = <function> defined @ConRO/helper.lua:310
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @ConRO/core.lua:2427
 ClearAbilityRaidBuffsIndependent = <function> defined @ConRO/buttons.lua:2719
 CreateRaidBuffsOverlay = <function> defined @ConRO/buttons.lua:1546
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @ConRO/helper.lua:241
 DisplayNext2WindowFrame = <function> defined @ConRO/buttons.lua:900
 NewModule = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 GlowNextDef = <function> defined @ConRO/buttons.lua:2920
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @ConRO/buttons.lua:1216
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @ConRO/helper.lua:732
 Dump = <function> defined @ConRO/buttons.lua:2627
 Colors = <table> {
 }
 RaidBuff = <function> defined @ConRO/helper.lua:398
 ClearAbilityInterruptIndependent = <function> defined @ConRO/buttons.lua:2695
 ToggleDamage = <function> defined @ConRO/buttons.lua:718
 Disable = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @ConRO/core.lua:2287
 Print = <function> defined @ConRO/core.lua:2036
 BurstMode = <function> defined @ConRO/helper.lua:79
 LEARNED_SPELL_IN_TAB = <function> defined @ConRO/core.lua:2362
 HideTauntGlow = <function> defined @ConRO/buttons.lua:1983
 HideDefenseGlow = <function> defined @ConRO/buttons.lua:1959
 CreateBurstButton = <function> defined @ConRO/buttons.lua:483
 Totem = <function> defined @ConRO/helper.lua:990
 SlashUnlock = <function> defined @ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @ConRO/helper.lua:816
 EnableModule = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @AckisRecipeList/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 RaidBuffsFramePool = <table> {
 }
 DefenseFramePool = <table> {
 }
 BlockAoE = <function> defined @ConRO/buttons.lua:759
 Interrupt = <function> defined @ConRO/helper.lua:928
 ButtonFetch = <function> defined @ConRO/core.lua:2362
 ACTIONBAR_HIDEGRID = <function> defined @AddOns`

**Comment by Vae2009** [comment]
Will be fixed in v10.0.4
