### ISSUE TITLE
Error on... well, panicking.

### ISSUE THREAD

**Issue by ghost** [Vae2009/ConRO_Druid#2]
I got shot down in Dragonbane Keep, frantically trying to hit cat form before I landed. I manged to hit a lot of buttons, ended up in bear form with this error, which threw again when I reloaded.

`9x ConRO_Druid/druid.lua:581: attempt to compare nil with number
[string "@ConRO_Druid/druid.lua"]:581: in function `NextSpell'
[string "@ConRO/core.lua"]:2433: in function `?'
[string "@DataStore/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
_ = <table> {
 AbilityPurge = <function> defined @ConRO/buttons.lua:2763
 IsPvP = <function> defined @ConRO/helper.lua:50
 Dragonriding = <function> defined @ConRO/helper.lua:1133
 DestroyPurgableOverlays = <function> defined @ConRO/buttons.lua:1684
 modules = <table> {
 }
 CancelTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 AbilityInterrupt = <function> defined @ConRO/buttons.lua:2723
 ItemEquipped = <function> defined @ConRO/helper.lua:147
 PurgeWindowFrame = <function> defined @ConRO/buttons.lua:1047
 InterruptGlow = <function> defined @ConRO/buttons.lua:1847
 ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @ConRO/helper.lua:69
 CreateDefenseOverlay = <function> defined @ConRO/buttons.lua:1254
 Heroism = <function> defined @ConRO/helper.lua:434
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @ConRO/core.lua:2467
 ClearAbilityRaidBuffsIndependent = <function> defined @ConRO/buttons.lua:2692
 CreateRaidBuffsOverlay = <function> defined @ConRO/buttons.lua:1518
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @ConRO/helper.lua:365
 UNIT_ENTERED_VEHICLE = <function> defined @ConRO/core.lua:2253
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 ACTIONBAR_PAGE_CHANGED = <function> defined @ConRO/core.lua:2408
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @ConRO/buttons.lua:1188
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @ConRO/helper.lua:858
 Dump = <function> defined @ConRO/buttons.lua:2600
 Colors = <table> {
 }
 RaidBuff = <function> defined @ConRO/helper.lua:524
 ClearAbilityInterruptIndependent = <function> defined @ConRO/buttons.lua:2668
 ToggleDamage = <function> defined @ConRO/buttons.lua:718
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @ConRO/core.lua:2309
 Print = <function> defined @ConRO/core.lua:2017
 BurstMode = <function> defined @ConRO/helper.lua:81
 LEARNED_SPELL_IN_TAB = <function> defined @ConRO/core.lua:2408
 HideTauntGlow = <function> defined @ConRO/buttons.lua:1955
 DefFetchDiabolic = <function> defined @ConRO/buttons.lua:2510
 CreateBurstButton = <function> defined @ConRO/buttons.lua:483
 Totem = <function> defined @ConRO/helper.lua:1121
 SlashUnlock = <function> defined @ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @ConRO/helper.lua:945
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 RaidBuffsFramePool = <table> {
 }
 DefenseFramePool = <table> {
 }
 BlockAoE = <function> defined @ConRO/buttons.lua:759
 Interrupt = <function> defined @ConRO/helper.lua:1059
 UpdateButtonGlow = <function> defined @ConRO/buttons.lua:1786
 ACTIONBAR_HIDEGRID = <function> defined @ConRO/core.lua:2235
 defaultModuleState = true
 Warnings = <fun`

**Comment by Vae2009** [comment]
Found the issue, and fixed in next update v10.0.7

**Comment by ghost** [comment]
Similar but not quite the same, this time when just changing specs in town. Equipped some new gear in Guardian, swapped to Feral and updated that gear, then got this error going back to Guardian.

`2x ConRO_Druid/druid.lua:581: attempt to compare nil with number
[string "@ConRO_Druid/druid.lua"]:581: in function `NextSpell'
[string "@ConRO/core.lua"]:2458: in function `?'
[string "@DataStore/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
_ = <table> {
 AbilityPurge = <function> defined @ConRO/buttons.lua:2763
 IsPvP = <function> defined @ConRO/helper.lua:51
 Dragonriding = <function> defined @ConRO/helper.lua:1158
 DestroyPurgableOverlays = <function> defined @ConRO/buttons.lua:1684
 modules = <table> {
 }
 CancelTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DefFetchBlizzard = <function> defined @ConRO/buttons.lua:2238
 ItemEquipped = <function> defined @ConRO/helper.lua:148
 PurgeWindowFrame = <function> defined @ConRO/buttons.lua:1047
 InterruptGlow = <function> defined @ConRO/buttons.lua:1847
 ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @ConRO/helper.lua:70
 CreateDefenseOverlay = <function> defined @ConRO/buttons.lua:1254
 Heroism = <function> defined @ConRO/helper.lua:459
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @ConRO/core.lua:2492
 ClearAbilityRaidBuffsIndependent = <function> defined @ConRO/buttons.lua:2692
 CreateRaidBuffsOverlay = <function> defined @ConRO/buttons.lua:1518
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @ConRO/helper.lua:390
 UnregisterAllEvents = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 ACTIONBAR_PAGE_CHANGED = <function> defined @ConRO/core.lua:2433
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @ConRO/buttons.lua:1188
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @ConRO/helper.lua:883
 Dump = <function> defined @ConRO/buttons.lua:2600
 Colors = <table> {
 }
 RaidBuff = <function> defined @ConRO/helper.lua:549
 ClearAbilityInterruptIndependent = <function> defined @ConRO/buttons.lua:2668
 ToggleDamage = <function> defined @ConRO/buttons.lua:718
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @ConRO/core.lua:2334
 Print = <function> defined @ConRO/core.lua:2017
 BurstMode = <function> defined @ConRO/helper.lua:82
 LEARNED_SPELL_IN_TAB = <function> defined @ConRO/core.lua:2433
 HideTauntGlow = <function> defined @ConRO/buttons.lua:1955
 DefFetchDiabolic = <function> defined @ConRO/buttons.lua:2510
 CreateBurstButton = <function> defined @ConRO/buttons.lua:483
 Totem = <function> defined @ConRO/helper.lua:1146
 SlashUnlock = <function> defined @ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @ConRO/helper.lua:970
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 RaidBuffsFramePool = <table> {
 }
 DefenseFramePool = <table> {
 }
 BlockAoE = <function> defined @ConRO/buttons.lua:759
 Interrupt = <function> defined @ConRO/helper.lua:1084
 UpdateButtonGlow = <function> defined @ConRO/buttons.lua:1786
 ACTIONBAR_HIDEGRID = <function> defined @ConRO/core.lua:2244`
